apiVersion: v1
kind: Service
metadata:
  name: {{ include "rag-poc-hmrc-demo.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "rag-poc-hmrc-demo.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
  selector:
    app.kubernetes.io/name: {{ include "rag-poc-hmrc-demo.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
